syms eta_I eta_V eta_F eta_L
syms Yii h_F
syms sigma_I sigma_V xi_T_f sigma_L_y
syms m

A = [exp(-eta_I*(Yii)), -exp(-eta_V*(Yii)), -exp(eta_V*(Yii)), 0, 0, 0; ...
    0, 1, 1, -1, -1, 0; ...
    0, 0, 0, exp(eta_F*h_F),exp(-eta_F*h_F), -exp(-eta_L*h_F); ...
    sigma_I*eta_I*exp(-eta_I*(Yii)), -sigma_V*eta_V*exp(-eta_V*(Yii)), sigma_V*eta_V*exp(eta_V*(Yii)), 0, 0, 0; ...
    0, sigma_V*eta_V, -sigma_V*eta_V, -xi_T_f*eta_F, xi_T_f*eta_F, 0; ...
    0, 0, 0, xi_T_f*eta_F*exp(eta_F*h_F), -xi_T_f*eta_F*exp(-eta_F*h_F), sigma_L_y*eta_L*exp(-eta_L*h_F)];

B = [m/(2*eta_V); ...
    -m/(2*eta_V)*exp(-eta_V*Yii); ...
    0; ...
    m*sigma_V/2; ...
    m*sigma_V/2*exp(-eta_V*Yii); ...
    0];

C = A\B;

C = simplify(C,'Steps',1000);
C = simplify(C,'Steps',1000);
